config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'page#home'

  get '/team', to: 'page#team'
  get '/contact', to: 'page#contact'
  get '/welcome/:first_name', to: 'page#welcome'
  get '/index/:x', to: 'page#potin'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def team
	end

	def contact

	end

	def home
		@gossip = Gossip.all
	end

	def welcome
		@name = params[:first_name]
	end

	def potin
		@potin = Gossip.find(params[:x].to_i)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand text-primary" href= "<%= root_path %>" >Gossip</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=" <%= team_path %> ">Team<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= contact_path %> ">contact</a>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/page/contact.html.erb
<h1 class="text-success"> Page de contact</h1>

<p>clique<a href = "mailto:franklinrazafy@gmail.com"> ici </a>pour envoyer un email</p>

app/views/page/home.html.erb
<h1 class="text-warning container">Hello BG 😀 😂 welcome to gossip page</h1></br>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Author_id</th>
      <th scope="col">Author</th>
      <th scope="col">Content</th>
      <th scope="col">Lien</th>
    </tr>
  </thead>
  <tbody>
  	<% @gossip.each do |gossip| %>
    <tr>
    
      <th scope="row" class="text-white"><%= gossip.id %></th>
      <td class="text-white"><%= gossip.author %></td>
      <td class="text-white"><%= gossip.content %></td>
      <td><a href = "/index/<%= gossip.id %>" class = "btn btn-primary"> page du potin</a></td>


    </tr>
        <% end %>
  </tbody>
</table>

app/views/page/potin.html.erb
<h1 class = "text-info">Vous etes sur la page du potin n°<%= @potin.id %></h1>

<h3>Author du potin: <%= @potin.author %></h3>
<h3>contenue: <%= @potin.content %></h3>

<p>Revenir à la <a href = "<%= root_path %>" class = "btn btn-primary"> page </a>des d'accueil</p>

app/views/page/team.html.erb
<h1 class="text-primary">Page de l'équipe</h1>

<h2> voici notre équipe lol mdr 🤟 😂 🤩 😘</h2>
 

app/views/page/welcome.html.erb
<h1>Salut <%= @name %> </h1>